#!/usr/bin/env sh
# Builds and runs commands in the docker container:
#
# Obtain an interactive session:
# ./ci/run_docker it
#
# Build and run the benchmarks
# ./ci/run_docker ...options (see ./ci/run)...
set -e

IMG=barneshut:latest

GPUS=""
if command nvidia-smi ; then
    export GPU="nv"
    GPUS="--gpus=all"
fi
if command rocm-smi ; then
    export GPU="amd"
    GPUS="--device=/dev/kfd --device=/dev/dri/renderD128 --shm-size 16G --group-add 109"
fi

if command xpu-smi ; then
    export GPU="intel"
    # GPUS=...TODO...
fi

# Build container
hpccm --recipe=ci/recipe.py --userarg gpu=$GPU | docker build -t $IMG -

DOCKER_CMDS="\
       -it \
       -u $(id -u):$(id -g) \
       -h $(hostname) \
       -v $(pwd):/src \
       -w /src \
       ${GPUS} \
       --privileged \
       --network=host \
       --cap-add=SYS_PTRACE \
       --security-opt seccomp=unconfined \
       -e RUN_ONLY:"${RUN_ONLY}" \
       -e BUILD_ONLY:"${BUILD_ONLY}" \
       -e GPU:"${GPU}" \
       $IMG \
"

case $1 in
    it)
        # Run container interactively:
        docker run $DOCKER_CMDS
        ;;
    fmt)
        # Format the code using the container's clang-format:
        docker run $DOCKER_CMDS bash -c "set -ex && ./ci/fmt"
        ;;
    thuering)
        # Format the code using the container's clang-format:
        docker run $DOCKER_CMDS bash -c "set -ex && ./ci/thuering $1 $2 $3 $4 "
        ;;
    bench_detail)
        # Format the code using the container's clang-format:
        docker run $DOCKER_CMDS bash -c "set -ex && GPU=${GPU} ./ci/benchmark_detailed 2>&1 | tee out_detail_$(hostname)"
        ;;
    bench_shmoo)
        # Format the code using the container's clang-format:
        docker run $DOCKER_CMDS bash -c "set -ex && GPU=${GPU} ./ci/bench_shmoo 2>&1 | tee out_shmoo_$(hostname)"
        ;;
    bench)
        # Format the code using the container's clang-format:
        docker run $DOCKER_CMDS bash -c "set -ex && GPU=${GPU} ./ci/benchmark 2>&1 | tee out_$(hostname)"
        ;;
    *)
        # Run container:
        docker run $DOCKER_CMDS \
            bash -c "set -ex && \
                       GPU=${GPU} \
                       RUN_ONLY=$RUN_ONLY \
                       BUILD_ONLY=$BUILD_ONLY \
                       ./ci/run $1 $2 $3 $4 $5 $6 $7 $8 $9"
        ;;
esac
